# Generated by Django 5.2.8 on 2025-11-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='votes_count',
            new_name='votes',
        ),
    ]
